#!/bin/bash
#PBS -k o
#PBS -N cfostemadgraph
#PBS -l nodes=1:ppn=48
#PBS -l walltime=7:00:00:00
#PBS -m abe
#PBS -M cfoste71@students.kennesaw.edu
#PBS -j oe
#PBS -q batch
JOBID=$( echo ${PBS_JOBID} | cut -f1 -d. )

sleep 10 
cd ${PBS_O_WORKDIR}
module load MG5_aMC
./../../MG5_aMC_v3_5_0/bin/mg5_aMC generate.sh
#./../../MG5_aMC_v3_5_0/bin/mg5_aMC run.sh

mv ../../cfostemadgraph.o$JOBID .

exit 0 
